### ISSUE TITLE
build with ghc-8.10.2

### ISSUE THREAD

**Issue by jwaldmann** [letmaik/monadiccp#13]
for 0.7.7 branch, with ghc-8.10.2 and stackage nightly-2020-10-31

```
monadiccp       > [ 7 of 63] Compiling Control.CP.SearchTree
monadiccp       >      
monadiccp       > /tmp/stack-3aa44fdabb3e7b1a/monadiccp-0.7.7/src/Control/CP/SearchTree.hs:203:10: error:
monadiccp       >     • Illegal nested constraint ‘Solver (TreeSolver m)’
monadiccp       >       (Use UndecidableInstances to permit this)
monadiccp       >     • In the instance declaration for ‘MonadTree (ContT r m)’
monadiccp       >     |
monadiccp       > 203 | instance (MonadTree m, Solver (TreeSolver m)) => MonadTree (ContT r m) where
monadiccp       >     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jwaldmann** [comment]
and more 8.10.2 errors, e.g.,
```
src/Control/Monatron/AutoInstances.hs:12:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
```
I'm gonna try to fix all of this and send PR.

The question is, how much backwards compatibility do we want?
* ghc-8.8? (probably, that's current stackage LTS). 
* ghc-8.6 as well? (I don't need it)

**Comment by jwaldmann** [comment]
blocked on https://gitlab.haskell.org/ghc/ghc/-/issues/18914

**Comment by jwaldmann** [comment]
The work-around is to expand some type synonyms   cfa45caf390750edd1255cd67b8638ffa2d5f023 , see https://gitlab.haskell.org/ghc/ghc/-/issues/18914#note_310314

The code now works for ghc-8.{4,6,10} but not ghc-8.8 - which needs an additional kind signature cb43c61c2032335ba3313920847f02ad8d0b0976
